### ISSUE TITLE
Something's wrong with Views.grid

### ISSUE THREAD

**Issue by laynor** [JaggerJo/Avalonia.FuncUI#14] opened 2019-07-17 08:08 UTC
I tried modifying your counter example code to use a grid instead of a dock panel:
```fsharp
    let view (state : CounterState) (dispatch) : View =
        Views.grid [
            Attrs.rowDefinitions (RowDefinitions "1*,1*")
            Attrs.columnDefinitions (ColumnDefinitions "1*, 1*")
            Attrs.children [
                Views.button [
                    // Attrs.dockPanel_dock Dock.Bottom
                    Attrs.grid_row 1
                    Attrs.grid_column 0
                    Attrs.onClick (fun sender args -> dispatch Decrement)
                    Attrs.content "-"
                ]
                Views.button [
                    // Attrs.dockPanel_dock Dock.Bottom
                    Attrs.grid_row 1
                    Attrs.grid_column 1
                    Attrs.onClick (fun sender args -> dispatch Increment)
                    Attrs.content "+"
                ]
                Views.textBlock [
                    // Attrs.dockPanel_dock Dock.Top
                    Attrs.grid_row 0
                    Attrs.grid_column 0
                    Attrs.grid_columnSpan 2
                    Attrs.fontSize 48.0
                    Attrs.verticalAlignment VerticalAlignment.Center
                    Attrs.horizontalAlignment HorizontalAlignment.Center
                    Attrs.text (string state.count)
                ]
            ]
        ]
```

The state is not updated anymore - the update function always gets the initial state for some reason. 

The issue is with these two lines:
```fsharp
            Attrs.rowDefinitions (RowDefinitions "1*,1*")
            Attrs.columnDefinitions (ColumnDefinitions "1*, 1*")
```
I get this error:
```
testafb3 Error: 0 : Unable to process the message: Increment: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Reassigning RowDefinitions not yet implemented.
   at Avalonia.Controls.Grid.set_RowDefinitions(RowDefinitions value) in D:\a\1\s\src\Avalonia.Controls\Grid.cs:line 131
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Avalonia.FuncUI.VirtualDom.Patcher.AttrPatcher.setValue@373(IControl view, PropertyAttrDelta attr, Object value)
   at Avalonia.FuncUI.VirtualDom.Patcher.AttrPatcher.patchProperty(IControl view, PropertyAttrDelta attr)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.Hosts.HostWindow.Avalonia-FuncUI-Hosts-IViewHost-UpdateView(View viewElement)
   at Avalonia.FuncUI.Elmish.Program.withHost@11.Invoke(model state, FSharpFunc`2 dispatch)
   at Elmish.ProgramModule.dispatch@132.Invoke(msg msg) in /Users/eugene/sources/elmish/elmish/src/program.fs:line 142
```

Is there a way to avoid this issue?

**Comment by JaggerJo** [comment] 2019-07-17 09:26
Hah, will look into this soon.

I guess Grid doesn’t support reassigning row/column definitions. And thats only a problem because RowDefinitions and ColumnDefinitions use reference equality  (by accident I guess).

A simple workaround for now would be to keep the RowDefinitions and ColumnDefinitions in a field...

**Comment by laynor** [comment] 2019-07-17 09:34
Thanks for the workaround!
I still have to get a decent dev env setup (cannot step into  library calls with the debugger yet), hope to give some better contributions in the future!

**Comment by JaggerJo** [comment] 2019-07-17 19:11
Great to hear, all contributions are welcome :)

The issue is related to Avalonia. I've made a PR that adds custom equality to

- ColumnDefinition
- ColumnDefinitions
- RowDefinition
- RowDefinitions
- SolidColorBrush
- ImmutableSolidColorBrush

This will solve the issue, but not the true source which is that row/column definitions cant be changed, but this might be different in the current nightly builds. You can try those, they work with the same FuncUI NuGet.

https://github.com/AvaloniaUI/Avalonia/pull/2747

**Comment by JaggerJo** [comment] 2019-07-25 17:31
Custom equality comparisons need to be added to FuncUI. I’m currently super busy so if the workaround works for you I’ll not hurry to fix it. (but it will be fixed in a month - latest).

If you actually are using it or really want it either tell me and I’ll do my best to fix it faster OR fix it and make a PR 😉.

**Comment by JaggerJo** [comment] 2019-08-25 12:06
will be fixed in 'v-next'.

**Closed by JaggerJo** 2019-08-25 12:06 UTC
